import type { Week, TopicIndex } from "./types"

export const roadmapMeta = {
  title: "AI Engineer Roadmap 2026",
  source: "Codebasics.io",
  totalWeeks: 32,
  duration: "8 Months (4 hours/day, 6 days/week)",
  description:
    "A comprehensive roadmap for AI Engineer, ML Engineer, or Gen AI Engineer based on analysis of hundreds of AI jobs.",
}

export const weeks: Week[] = [
  {
    week: 1,
    title: "AI Basics + Beginners Python",
    focus: "Understanding AI landscape and Python fundamentals",
    topics: [
      "AI Basics - ML, DL, NLP, Gen AI, Agentic AI",
      "Variables, Numbers, Strings",
      "Lists, Dictionaries, Sets, Tuples",
      "If condition, for loop",
      "Functions, Lambda Functions",
      "Modules (pip install)",
      "Read, Write files",
      "Exception handling",
      "Classes, Objects",
    ],
    resources: [
      { type: "video", title: "AI Basics", url: "https://www.youtube.com/watch?v=VGFpV3Qj4as" },
      { type: "playlist", title: "Python Tutorials (Codebasics)", url: "https://bit.ly/3X6CCC7" },
      { type: "playlist", title: "Corey's Python Tutorials", url: "https://bit.ly/3uqUgaZ" },
      {
        type: "course",
        title: "AI Bootcamp (Paid)",
        url: "https://codebasics.io/bootcamps/ai-data-science-bootcamp-with-virtual-internship",
      },
    ],
    assignments: ["Finish Python exercises: https://bit.ly/3k1mof5", "Create a professional-looking LinkedIn profile"],
    coreSkills: ["Create LinkedIn profile with clear picture and banner", "Use LinkedIn Checklist"],
  },
  {
    week: 2,
    title: "Data Structures and Algorithms",
    focus: "DSA fundamentals in Python",
    topics: [
      "Data structures basics, Big O notation",
      "Arrays, Hash Table, Linked List",
      "Stack, Queue, Tree, Graph",
      "Binary search, Bubble sort",
      "Recursion",
    ],
    resources: [{ type: "playlist", title: "DSA YouTube Playlist", url: "https://bit.ly/3uiW2Lf" }],
    assignments: ["Finish all DSA exercises in playlist"],
    coreSkills: ["Start attending Toastmasters for communication"],
    motivation: ["Conversation with Senior Director of Fractal: https://www.youtube.com/watch?v=BaAA7kNjeZw"],
  },
  {
    week: 3,
    title: "Advanced Python",
    focus: "Advanced Python concepts",
    topics: [
      "Inheritance, Generators, Iterators",
      "List Comprehensions, Decorators",
      "Multithreading, Multiprocessing",
    ],
    resources: [{ type: "playlist", title: "Python Tutorials (17-27)", url: "https://bit.ly/3X6CCC7" }],
    assignments: [
      "Finish advanced Python exercises",
      "Write meaningful comments on 10 AI-related LinkedIn posts",
      "Note key learnings from 3 ThinkSchool case studies",
    ],
    coreSkills: [
      "Follow AI influencers on LinkedIn",
      "Increase engagement - comment meaningfully",
      "Learn business fundamentals from ThinkSchool",
      "Join Discord communities",
    ],
  },
  {
    week: 4,
    title: "Version Control (Git, GitHub)",
    focus: "Mastering version control",
    topics: [
      "What is version control? Git and GitHub",
      "Basic commands: add, commit, push",
      "Branches, reverting changes, HEAD",
      "Diff and Merge",
      "Pull requests",
    ],
    resources: [
      { type: "playlist", title: "Git Tutorial (Codebasics)", url: "https://bit.ly/3SECQQ7" },
      { type: "playlist", title: "Git Tutorial (Corey)", url: "https://bit.ly/3T0Yrmb" },
    ],
    assignments: ["Write 2 meaningful blog posts on AI tech topics", "Build teaching skills through content creation"],
    coreSkills: ["Presentation skills - Death by PowerPoint: https://youtu.be/Iwpi1Lm6dFo"],
  },
  {
    week: 5,
    title: "NumPy, Pandas, Data Visualization, SQL",
    focus: "Data manipulation and querying",
    topics: [
      "NumPy arrays and operations",
      "Pandas DataFrames",
      "Matplotlib, Seaborn visualization",
      "SQL Basics: SELECT, WHERE, LIKE, DISTINCT",
      "GROUP BY, ORDER BY, BETWEEN",
      "Joins: Left, Right, Inner, Full",
    ],
    resources: [
      {
        type: "course",
        title: "Math and Statistics Course (Ch 4-5)",
        url: "https://codebasics.io/courses/math-and-statistics-for-data-science",
      },
      { type: "video", title: "SQL Tutorial", url: "https://www.youtube.com/watch?v=Rm0xH2Vpfi0" },
    ],
    assignments: ["Complete NumPy, Pandas exercises", "Practice SQL queries"],
  },
  {
    week: 6,
    title: "Math & Statistics for AI (Part 1)",
    focus: "Statistical foundations",
    topics: [
      "Descriptive vs inferential statistics",
      "Continuous vs discrete data",
      "Nominal vs ordinal data",
      "Basic plots: Histograms, pie charts, bar charts, scatter",
      "Measures of central tendency: mean, median, mode",
    ],
    resources: [
      {
        type: "course",
        title: "Khan Academy Statistics",
        url: "https://www.khanacademy.org/math/statistics-probability",
      },
      { type: "playlist", title: "StatQuest YouTube", url: "https://www.youtube.com/@statquest" },
      { type: "playlist", title: "Statistics Playlist", url: "https://bit.ly/3QrSXis" },
    ],
    assignments: ["Finish statistics exercises"],
  },
  {
    week: 7,
    title: "Math & Statistics for AI (Part 2)",
    focus: "Linear algebra and calculus",
    topics: [
      "Vectors and Matrices",
      "Eigenvalues and Eigenvectors",
      "Basics of integral and differential calculus",
      "Measures of dispersion: variance, standard deviation",
    ],
    resources: [
      { type: "playlist", title: "3Blue1Brown", url: "https://www.youtube.com/@3blue1brown" },
      {
        type: "course",
        title: "Math for Data Science",
        url: "https://codebasics.io/courses/math-and-statistics-for-data-science",
      },
    ],
    assignments: ["Practice linear algebra problems", "Complete calculus exercises"],
  },
  {
    week: 8,
    title: "Math & Statistics for AI (Part 3)",
    focus: "Probability and hypothesis testing",
    topics: [
      "Basics of Probability",
      "Normal distribution",
      "Correlation and covariance",
      "Central limit theorem",
      "Hypothesis testing: p value, confidence interval",
      "Type 1 vs Type 2 error, Z test",
    ],
    resources: [
      {
        type: "course",
        title: "Khan Academy Probability",
        url: "https://www.khanacademy.org/math/statistics-probability",
      },
    ],
    assignments: ["Complete all Khan Academy exercises", "Finish probability problems"],
  },
  {
    week: 9,
    title: "Machine Learning (Part 1)",
    focus: "ML fundamentals and preprocessing",
    topics: [
      "Is statistical ML still relevant in Gen AI era?",
      "Handling NA values, outlier treatment",
      "Data normalization",
      "One hot encoding, label encoding",
      "Feature engineering",
      "Train test split, Cross validation",
    ],
    resources: [
      { type: "playlist", title: "ML YouTube Playlist", url: "https://bit.ly/3io5qqX" },
      { type: "playlist", title: "Feature Engineering", url: "https://bit.ly/3IFa3Yf" },
    ],
    assignments: ["Complete ML exercises", "Work on Kaggle notebooks"],
  },
  {
    week: 10,
    title: "Machine Learning (Part 2)",
    focus: "Supervised learning models",
    topics: [
      "Types of ML: Supervised vs Unsupervised",
      "Regression vs Classification",
      "Linear regression, Logistic regression",
      "Gradient descent",
      "Decision tree, Random forest",
      "XGBoost",
    ],
    resources: [{ type: "playlist", title: "ML Playlist (First 21 videos)", url: "https://bit.ly/3io5qqX" }],
    assignments: ["Build regression and classification models", "Write LinkedIn posts on ML"],
  },
  {
    week: 11,
    title: "Machine Learning (Part 3)",
    focus: "Model evaluation and unsupervised learning",
    topics: [
      "Model evaluation metrics",
      "Regression: MSE, MAE, MAPE",
      "Classification: Accuracy, Precision, Recall, F1, ROC, Confusion Matrix",
      "Hyperparameter tuning: GridSearchCV, RandomSearchCV",
      "Unsupervised: K means, DBScan, PCA",
    ],
    resources: [
      {
        type: "course",
        title: "AI Bootcamp",
        url: "https://codebasics.io/bootcamps/ai-data-science-bootcamp-with-virtual-internship",
      },
    ],
    assignments: ["Complete all ML playlist exercises", "Help 10 people on Discord"],
    coreSkills: ["Project Management: Scrum, Kanban", "Tools: JIRA, Notion"],
  },
  {
    week: 12,
    title: "DevOps, MLOps, FastAPI (Part 1)",
    focus: "API development and ML operations",
    topics: ["What is API? FastAPI for Python", "What is MLOps?", "Experiment Tracking with MLFlow"],
    resources: [
      { type: "video", title: "FastAPI Tutorial", url: "https://bit.ly/497p6Ex" },
      { type: "video", title: "What is MLOps", url: "https://bit.ly/3R4uGA0" },
      { type: "video", title: "MLFlow Tutorial", url: "https://www.youtube.com/watch?v=6ngxBkx05Fs" },
    ],
    assignments: ["Build a FastAPI application", "Track experiments with MLFlow"],
  },
  {
    week: 13,
    title: "DevOps, MLOps, FastAPI (Part 2)",
    focus: "Containerization and cloud basics",
    topics: [
      "CI/CD pipelines",
      "Containerization: Docker, Kubernetes",
      "Cloud platforms: AWS or Azure basics",
      "Start contributing to opensource",
    ],
    resources: [
      { type: "video", title: "Docker Tutorial", url: "https://bit.ly/3uCNpeE" },
      { type: "tool", title: "MindSQL Issues", url: "https://github.com/Mindinventory/MindSQL/issues" },
      { type: "tool", title: "RagRank Issues", url: "https://github.com/izam-mohammed/ragrank" },
    ],
    assignments: ["Learn Docker basics", "Find and work on a 'Good first issue'"],
    motivation: ["ML Engineer after 12th: https://bit.ly/3DqwLTY"],
  },
  {
    week: 14,
    title: "Machine Learning Projects",
    focus: "End-to-end ML project implementation",
    topics: [
      "Data cleaning and feature engineering",
      "Model building and hyperparameter tuning",
      "Flask/FastAPI server as web backend",
      "Building prediction website",
      "Deployment to AWS",
    ],
    resources: [
      { type: "playlist", title: "Bangalore Price Prediction", url: "https://bit.ly/3ivycWr" },
      { type: "video", title: "FastAPI Tutorial", url: "https://youtu.be/Wr1JjhTt1Xg" },
    ],
    assignments: [
      "Use FastAPI instead of Flask",
      "Build classification project with Kaggle dataset",
      "Deploy to AWS or Azure",
      "Add project links to resume and LinkedIn",
    ],
    coreSkills: ["ATS Resume Preparation", "Portfolio Building with GitHub"],
  },
  {
    week: 15,
    title: "Deep Learning (Part 1)",
    focus: "Neural network fundamentals",
    topics: ["What is a neural network?", "Forward propagation, Back propagation", "Building multilayer perceptron"],
    resources: [
      { type: "playlist", title: "Deep Learning (TensorFlow)", url: "https://bit.ly/3vOZ3zV" },
      { type: "playlist", title: "PyTorch Playlist (CampusX)", url: "https://bit.ly/3K353Qg" },
    ],
    assignments: ["Build basic neural networks", "Understand backpropagation"],
  },
  {
    week: 16,
    title: "Deep Learning (Part 2)",
    focus: "Convolutional Neural Networks",
    topics: ["CNN architecture", "Convolutional layers, Pooling", "Image classification"],
    resources: [{ type: "playlist", title: "Deep Learning Playlist", url: "https://bit.ly/3vOZ3zV" }],
    assignments: ["Build CNN for image classification"],
  },
  {
    week: 17,
    title: "Deep Learning (Part 3)",
    focus: "Sequence models",
    topics: ["Sequence models: RNN, LSTM", "Time series prediction", "Text sequence modeling"],
    resources: [{ type: "playlist", title: "Deep Learning Playlist", url: "https://bit.ly/3vOZ3zV" }],
    assignments: ["Build RNN/LSTM model for sequence data"],
  },
  {
    week: 18,
    title: "Deep Learning (Part 4)",
    focus: "Transformers and DL projects",
    topics: ["Transformer architecture", "Attention mechanism", "End-to-end DL project"],
    resources: [{ type: "project", title: "Potato Disease Classification", url: "https://bit.ly/3QzkVJi" }],
    assignments: [
      "Use different image dataset (tomato plant)",
      "Deploy to Azure instead of GCP",
      "Create stakeholder presentation and upload to LinkedIn",
    ],
  },
  {
    week: 19,
    title: "NLP or Computer Vision (Part 1)",
    focus: "Choose specialization track",
    topics: [
      "NLP Track: Regex, Text representation",
      "Count vectorizer, TF-IDF, BOW, Word2Vec",
      "CV Track: Basic image processing",
      "Filtering, Edge Detection, Scaling, Rotation",
    ],
    resources: [{ type: "playlist", title: "NLP YouTube Playlist", url: "https://bit.ly/3XnjfEZ" }],
    assignments: ["Choose NLP or CV track", "Complete initial exercises"],
  },
  {
    week: 20,
    title: "NLP or Computer Vision (Part 2)",
    focus: "Advanced techniques",
    topics: [
      "NLP: Text classification, Naive Bayes",
      "Spacy & NLTK libraries",
      "CV: OpenCV library",
      "YOLO for object detection",
    ],
    resources: [{ type: "playlist", title: "NLP Playlist", url: "https://bit.ly/3XnjfEZ" }],
    assignments: ["Build text classifier or object detector"],
  },
  {
    week: 21,
    title: "NLP or Computer Vision (Part 3)",
    focus: "End-to-end project",
    topics: [
      "NLP: Log Classification System",
      "Hybrid approach: regex, BERT, LR, LLM",
      "DB Scan clustering",
      "FastAPI Backend",
    ],
    resources: [{ type: "project", title: "Log Classification System", url: "https://bit.ly/4hu5EoL" }],
    assignments: ["Complete NLP or CV end-to-end project"],
  },
  {
    week: 22,
    title: "Gen AI and Agentic AI (Part 1)",
    focus: "LLM fundamentals",
    topics: ["What is LLM?", "Vector databases", "Embeddings", "RAG (Retrieval Augmented Generation)"],
    resources: [{ type: "video", title: "Gen AI Crash Course", url: "https://bit.ly/3Fn7Zoh" }],
    assignments: ["Understand LLM basics", "Build simple RAG system"],
  },
  {
    week: 23,
    title: "Gen AI and Agentic AI (Part 2)",
    focus: "Frameworks and tools",
    topics: ["Langchain framework", "MCP (Model Context Protocol)", "Agentic frameworks: LangGraph, CrewAI"],
    resources: [
      { type: "video", title: "What is MCP", url: "https://youtu.be/tzrwxLNHtRY" },
      { type: "video", title: "Build MCP Server", url: "https://youtu.be/jLM6n4mdRuA" },
      { type: "video", title: "LangGraph Tutorial", url: "https://www.youtube.com/watch?v=CnXdddeZ4tQ" },
    ],
    assignments: ["Build MCP server", "Create agent with LangGraph"],
  },
  {
    week: 24,
    title: "Gen AI and Agentic AI (Part 3)",
    focus: "Fine-tuning and advanced topics",
    topics: ["LLM Fine Tuning", "Advanced prompt engineering", "Agent orchestration"],
    resources: [
      { type: "video", title: "LLM Fine Tuning", url: "https://youtu.be/IIvORO248Zs" },
      { type: "video", title: "CrewAI Tutorial", url: "https://www.youtube.com/watch?v=G42J2MSKyc8" },
    ],
    assignments: ["Fine-tune a model", "Build multi-agent system"],
  },
  {
    week: 25,
    title: "Gen AI Projects (Part 1)",
    focus: "Real-world Gen AI applications",
    topics: ["LLM-powered applications", "RAG implementations", "Agent-based solutions"],
    resources: [{ type: "playlist", title: "Gen AI Project Playlist", url: "https://bit.ly/4ilzEnX" }],
    assignments: ["Start first Gen AI project"],
  },
  {
    week: 26,
    title: "Gen AI Projects (Part 2)",
    focus: "Advanced Gen AI projects",
    topics: ["Complex RAG systems", "Production-ready agents", "Integration patterns"],
    resources: [{ type: "playlist", title: "Gen AI Projects", url: "https://bit.ly/4ilzEnX" }],
    assignments: ["Complete second Gen AI project"],
  },
  {
    week: 27,
    title: "Gen AI Projects (Part 3)",
    focus: "Portfolio-ready projects",
    topics: ["End-to-end deployment", "Documentation", "Portfolio presentation"],
    resources: [{ type: "playlist", title: "Gen AI Projects", url: "https://bit.ly/4ilzEnX" }],
    assignments: ["Complete and document Gen AI projects"],
  },
  {
    week: 28,
    title: "Unguided AI Projects (Part 1)",
    focus: "Independent project work",
    topics: ["RAG Chatbot with RBAC", "Project planning and architecture", "Independent problem solving"],
    resources: [{ type: "project", title: "RAG Chatbot with RBAC", url: "https://bit.ly/47SttUq" }],
    assignments: ["Start unguided project with confidence"],
  },
  {
    week: 29,
    title: "Unguided AI Projects (Part 2)",
    focus: "NLP applications",
    topics: ["Adverse drug event detection", "NLP in healthcare", "Real-world data challenges"],
    resources: [{ type: "project", title: "Adverse Drug Events Detection", url: "https://bit.ly/43oup1y" }],
    assignments: ["Complete second unguided project", "Add to portfolio"],
  },
  {
    week: 30,
    title: "Azure or AWS (Part 1)",
    focus: "Cloud fundamentals",
    topics: [
      "Azure: Resource groups, subscriptions, regions, storage, IAM",
      "AWS: Accounts, regions, S3, IAM",
      "Cloud fundamentals",
    ],
    resources: [
      { type: "article", title: "Azure Documentation", url: "https://docs.microsoft.com/azure" },
      { type: "article", title: "AWS Documentation", url: "https://docs.aws.amazon.com" },
    ],
    assignments: ["Set up cloud account", "Learn fundamental services"],
  },
  {
    week: 31,
    title: "Azure or AWS (Part 2)",
    focus: "Compute and deployment",
    topics: ["Azure: Functions, App Service, AKS", "AWS: Lambda, App Runner, EKS", "Serverless architectures"],
    resources: [],
    assignments: ["Deploy application to cloud", "Use serverless functions"],
  },
  {
    week: 32,
    title: "Azure or AWS (Part 3)",
    focus: "AI/ML cloud services",
    topics: [
      "Azure: Azure ML, OpenAI Service, Cognitive Services",
      "AWS: SageMaker, Bedrock, AI Services",
      "MLOps: Pipelines, Model monitoring",
    ],
    resources: [],
    assignments: ["Use cloud AI services", "Set up ML pipeline"],
  },
]

export const topicsIndex: TopicIndex = {
  python: [1, 2, 3],
  "data structures": [2],
  algorithms: [2],
  git: [4],
  github: [4],
  numpy: [5],
  pandas: [5],
  sql: [5],
  visualization: [5],
  statistics: [6, 7, 8],
  math: [6, 7, 8],
  probability: [8],
  "machine learning": [9, 10, 11, 14],
  preprocessing: [9],
  "supervised learning": [10],
  "unsupervised learning": [11],
  devops: [12, 13],
  mlops: [12, 13],
  fastapi: [12, 14],
  docker: [13],
  "deep learning": [15, 16, 17, 18],
  cnn: [16],
  rnn: [17],
  lstm: [17],
  transformers: [18],
  nlp: [19, 20, 21],
  "computer vision": [19, 20, 21],
  "gen ai": [22, 23, 24, 25, 26, 27],
  llm: [22, 23, 24],
  rag: [22, 25],
  langchain: [23],
  agents: [23, 24],
  "fine tuning": [24],
  azure: [30, 31, 32],
  aws: [30, 31, 32],
  cloud: [30, 31, 32],
}
